<?php

define("CAMPO_VAZIO", -1);
define("CAMPO_NULL", null);

define("SEM_COMPANHIA_AEREA_DEFINIDA", CAMPO_NULL);
define("SEM_AERONAVE_DEFINIDA", CAMPO_NULL);
define("SEM_PILOTO_DEFINIDO", CAMPO_NULL);
define("SEM_COPILOTO_DEFINIDO", CAMPO_NULL);
define("SEM_COMISSARIO_DEFINIDO", CAMPO_NULL);
define("SEM_CODIGO_VOO_DEFINIDO", CAMPO_NULL);
define("SEM_HORARIO_EMBARQUE_DEFINIDO", CAMPO_NULL);
define("SEM_DURACAO_PERCURSO_DEFINIDA", CAMPO_NULL);

define("TAMANHO_REGISTRO", 6);


// define("TAMANHO_RG", 8);
define('VAZIO', '');

DEFINE('PESO_FRANQUIA_BAGAGEM', 23);

define("PILOTO", 1);
define("COMISSARIO", 2);
